"""Compile slide-friendly YAML regime files into Cedar policies.

A regime file reads like a compliance memo::

    regime: EU
    cite: GDPR Art. 5(1)(c) · DORA Art. 9(2)
    applies_to:
      jurisdictions: [DE, EU, UK]
    purposes: [fraud_investigation, regulatory_reporting, research]
    roles:
      fraud_analyst:
        analyze:  all fields
        decrypt:  none              # data minimisation
        identifiers: never

Each role becomes up to three Cedar policies (analyze permit, decrypt permit,
identifier forbid). ``purposes`` becomes one purpose-limitation forbid.
Every policy carries ``@id`` and ``@reason`` annotations, plus any
``@obligation_*`` annotations, so a decision can say *why* and *on what terms*.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

GENERATED_MARKER = "// GENERATED by blind-policy compile"

ALL = "all fields"
NONE = "none"
IDENTIFIERS_NEVER = "never"
IDENTIFIERS_ALLOWED = "allowed"

OBLIGATIONS = ("min_cohort",)  # closed set; engine.py knows how to merge each one


class PolicyFileError(ValueError):
    pass


def _purpose_label(purpose: str) -> str:
    return purpose.replace("treatment_operations", "treatment & operations").replace("_", " ")


def _q(value: str) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _set(values: list[str]) -> str:
    return "[" + ", ".join(_q(v) for v in values) + "]"


def _selector(raw: Any, sets: dict[str, list[str]], where: str) -> str | list[str]:
    """Normalize ``analyze`` / ``decrypt`` values to ALL, NONE, or a field-name list."""
    if raw is None:
        return NONE
    if isinstance(raw, list):
        return [str(v).strip() for v in raw if str(v).strip()]
    text = str(raw).strip()
    low = text.lower()
    if low in (ALL, "all"):
        return ALL
    if low in (NONE, "", "[]"):
        return NONE
    if text in sets:
        return list(sets[text])
    # Slide style: "risk_level, diagnosis_band"
    names = [part.strip() for part in text.split(",") if part.strip()]
    if not names:
        raise PolicyFileError(f"{where}: cannot read field selector {raw!r}")
    return names


def _scope(applies_to: dict[str, Any]) -> list[str]:
    clauses = []
    juris = [str(j).upper() for j in applies_to.get("jurisdictions") or []]
    if juris:
        clauses.append(f"{_set(juris)}.contains(principal.jurisdiction)")
    domains = [str(d) for d in applies_to.get("domains") or []]
    if domains:
        clauses.append(f"{_set(domains)}.contains(resource.domain)")
    return clauses


def _annotations(pid: str, regime: str, reason: str, obligations: dict[str, Any]) -> list[str]:
    lines = [f"@id({_q(pid)})", f"@regime({_q(regime)})", f"@reason({_q(reason)})"]
    for key in OBLIGATIONS:
        if key in obligations and obligations[key] is not None:
            lines.append(f"@obligation_{key}({_q(obligations[key])})")
    return lines


def _when(clauses: list[str]) -> str:
    if not clauses:
        return ""
    return " when {\n  " + " &&\n  ".join(clauses) + "\n}"


def _permit(
    *,
    pid: str,
    regime: str,
    reason: str,
    role: str,
    action: str,
    selector: str | list[str],
    identifiers: str,
    scope: list[str],
    obligations: dict[str, Any],
) -> str | None:
    if selector == NONE:
        return None
    clauses = list(scope)
    if selector == ALL:
        if identifiers != IDENTIFIERS_ALLOWED:
            clauses.append('resource.sensitivity != "identifier"')
    else:
        clauses.append(f"{_set(selector)}.contains(resource.name)")
    head = "\n".join(_annotations(pid, regime, reason, obligations))
    body = (
        "permit (\n"
        f"  principal in BI::Role::{_q(role)},\n"
        f"  action == BI::Action::{_q(action)},\n"
        "  resource is BI::Field\n"
        ")"
    )
    return f"{head}\n{body}{_when(clauses)};"


def compile_regime(data: dict[str, Any], *, source: str = "<yaml>") -> str:
    """Return Cedar source for one parsed regime file."""
    regime = str(data.get("regime") or "").strip()
    if not regime:
        raise PolicyFileError(f"{source}: 'regime' is required")
    cite = str(data.get("cite") or regime).strip()
    prefix = regime.lower().replace(" ", "_").replace("-", "_")
    scope = _scope(data.get("applies_to") or {})
    sets = {str(k): [str(v) for v in vals] for k, vals in (data.get("sets") or {}).items()}
    file_obligations = dict(data.get("obligations") or {})
    unknown = set(file_obligations) - set(OBLIGATIONS)
    if unknown:
        raise PolicyFileError(f"{source}: unknown obligations {sorted(unknown)}")

    out: list[str] = [f"// {regime}: {cite}"]

    purposes = [str(p) for p in data.get("purposes") or []]
    if purposes:
        purpose_cite = str(data.get("purpose_cite") or cite)
        head = "\n".join(
            _annotations(
                f"{prefix}.purpose_limitation",
                regime,
                f"{purpose_cite}: permitted purposes are "
                + ", ".join(_purpose_label(p) for p in purposes),
                {},
            )
        )
        cond = _when(scope)
        out.append(
            f"{head}\nforbid (principal, action, resource is BI::Field)"
            f"{cond}\nunless {{ {_set(purposes)}.contains(context.purpose) }};"
        )

    roles = data.get("roles") or {}
    if not roles:
        raise PolicyFileError(f"{source}: no roles defined")
    for role, spec in roles.items():
        spec = spec or {}
        where = f"{source}: roles.{role}"
        identifiers = str(spec.get("identifiers") or IDENTIFIERS_NEVER).strip().lower()
        if identifiers not in (IDENTIFIERS_NEVER, IDENTIFIERS_ALLOWED):
            raise PolicyFileError(f"{where}.identifiers must be 'never' or 'allowed'")
        obligations = {**file_obligations, **(spec.get("obligations") or {})}
        reason = str(spec.get("cite") or cite)
        analyze = _selector(spec.get("analyze"), sets, f"{where}.analyze")
        decrypt = _selector(spec.get("decrypt"), sets, f"{where}.decrypt")

        for action, selector, verb in (
            ("query_aggregate", analyze, "analyze"),
            ("decrypt", decrypt, "decrypt"),
        ):
            policy = _permit(
                pid=f"{prefix}.{role}.{verb}",
                regime=regime,
                reason=reason,
                role=role,
                action=action,
                selector=selector,
                identifiers=identifiers,
                scope=scope,
                obligations=obligations,
            )
            if policy:
                out.append(f"// {regime} · {role} · {verb}\n{policy}")

        if identifiers == IDENTIFIERS_NEVER:
            head = "\n".join(
                _annotations(
                    f"{prefix}.{role}.identifiers",
                    regime,
                    f"{reason}: identifiers never leave the proxy for this role",
                    {},
                )
            )
            clauses = [*scope, 'resource.sensitivity == "identifier"']
            out.append(
                f"// {regime} · {role} · identifiers: never\n{head}\n"
                "forbid (\n"
                f"  principal in BI::Role::{_q(role)},\n"
                '  action in [BI::Action::"query_aggregate", BI::Action::"decrypt"],\n'
                "  resource is BI::Field\n"
                f"){_when(clauses)};"
            )

    return "\n\n".join(out) + "\n"


def compile_file(path: str | Path) -> str:
    path = Path(path)
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    body = compile_regime(data, source=path.name)
    return f"{GENERATED_MARKER} from {path.name}. Edit the YAML, not this file.\n\n{body}"


def compile_dir(directory: str | Path, *, write: bool = False) -> dict[Path, str]:
    """Compile every ``*.yaml`` in a directory. With ``write``, save ``<name>.cedar`` alongside."""
    results: dict[Path, str] = {}
    for yml in sorted(Path(directory).glob("*.yaml")):
        text = compile_file(yml)
        target = yml.with_suffix(".cedar")
        results[target] = text
        if write:
            target.write_text(text, encoding="utf-8")
    return results
